
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/bbq
    username: root
    password: 12345678
    type: com.alibaba.druid.pool.DruidDataSource # 使用druid数据源
    driver-class-name: com.mysql.jdbc.Driver



mybatis:
  mapper-locations: classpath:mapper/*.xml  # mapper映射xml文件的所在路径
  type-aliases-package: com.biaobai.domain  # 实体类的路径

server:
  port: 9300

